version: '3'

services:
  api-node-playero:
    build:
      context: .  # Usa el Dockerfile en el directorio actual
      dockerfile: Dockerfile  # Nombre del Dockerfile
    image: node-api-playero-0.1.2:latest  # Nombre de la imagen
    container_name: node-api-playero-0.1.2  # Nombre del contenedor
    ports:
      - "4080:4080"  # Mapea el puerto externo 4080 al interno 4080
    restart: always  # Reinicia el contenedor automáticamente en caso de error
    volumes:
      - /home/administrador/APIS/shared:/home/administrador/APIS/shared  # Mapea la carpeta del host al contenedor
